### ISSUE TITLE
The PostFinance Checkout payment transaction is not set on the quote

### ISSUE THREAD

**Issue by sunilit42** [pfpayments/magento-2#13]
Hello,

Some time into log we are getting this error
The PostFinance Checkout payment transaction is not set on the quote

**Comment by theodorspringwallee** [comment]
Dear [sunilit42](https://github.com/sunilit42)

This error is thrown, when the wallee space ID or the wallee transaction ID couldn't be found in the `Magento\Quote\Model\Quote` object during the checkout process.

So, do you have uncompleted transactions in your magento order list?

Currently, in our showcase (https://magento-2.showcase-wallee.com/) we do not have issues during the checkout.

That we can help you individually, please get in touch with our support by contacting info@wallee.com

Best regards

**Comment by loryzz** [comment]
Dear @theodorspringwallee 
With the version 2.1.12 of the module (Magento 2.4.6-p5), the problem is present on all transactions, which cannot be completed due to the error: _The PostFinance Checkout payment transaction is not set on the quote_
I downgraded the module to the version 2.1.11 and it seems to work again.

**Comment by thibault-mambour** [comment]
Hi @loryzz , could you send this problem to [checkout@postfinance.ch](mailto:checkout@postfinance.ch) ? 
Thank you
