### ISSUE TITLE
two times invoice create happen

### ISSUE THREAD

**Issue by sunilit42** [pfpayments/magento-2#5]
Hello,

- can i know why you do manually create inoice then order successfully as same logic you did via webhook? 

- you are creating webhook on save configuration
- while order place you are doing invoice by code as well
- some time it is try to do generate two times

**Comment by theodorspringwallee** [comment]
Dear [sunilit42](https://github.com/sunilit42)

Since this seems a product question, please contact the PostFinance support: https://www.postfinance.ch/en/business/products/e-commerce/postfinance-checkout-all-in-one/postfinance-checkout-contact-and-support.html

Please also mention to them examples (transaction link, etc.), which confirms your descriptions.

Best regards

**Comment by sunilit42** [comment]
- no you are creating webhook when system config save, so lot of code doing calling again
sales_order_save event fire every time your webhook call
