### ISSUE TITLE
issu payment mode

### ISSUE THREAD

**Issue by royalkaroma** [pfpayments/magento-2#8]
hi i goth tis erreur pleas help me its the fresh install magento with symple data i tray more then 5 install

Synchronizing with PostFinance Checkout failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zb1un_app_magento.jn6r_postfinancecheckout_payment_method_configuration' doesn't exist, query was: SELECT `main_table`.* FROM `jn6r_postfinancecheckout_payment_method_configuration` AS `main_table` WHERE ((`state` IN(1, 2, 3)))

**Comment by bondazzi** [comment]
I think the problem is that they create the tables with the prefix "wallee_" but in the code then they call them with the prefix "postfinancecheckout_".

While waiting for a fix here, if you are still testing and if you are not using other modules that need the tables starting with the name "wallee_...", i think you can try to change the table names directly in the database.

From


wallee_payment_method_configuration
wallee_payment_refund_job
wallee_payment_token_info
wallee_payment_transaction_info

to

postfinancecheckout_payment_method_configuration
postfinancecheckout_payment_refund_job
postfinancecheckout_payment_token_info
postfinancecheckout_payment_transaction_info

**Comment by royalkaroma** [comment]
thank a lot i do the test but i got more problem
![Capture](https://user-images.githubusercontent.com/36032214/190584628-06e57629-dd2f-42d2-a6c0-b38accc0c275.PNG)

**Comment by bondazzi** [comment]
> I think the problem is that they create the tables with the prefix "wallee_" but in the code then they call them with the prefix "postfinancecheckout_"

Could you confirm if this error is present in the last version?
If yes, are you planning a new version with the fix?

**Comment by royalkaroma** [comment]
J ai tout supprimer la validation c est ok mais le mode de payement rien ne s affiche

**Comment by theodorspringwallee** [comment]
Dear [royalkaroma](https://github.com/royalkaroma), [bondazzi](https://github.com/bondazzi)

We saw this BUG already and are working on this. 

[royalkaroma](https://github.com/royalkaroma) this 401 error can be an authentication error. 

Please can you double-check if your space ID, application user ID, and application key is correct.

In addition, please also check the timestamp on your server, that may not deviate more than 15 mins to the current time, to be authenticated on the postfinance portal.

For further support please contact: https://www.postfinance.ch/en/support/hotline.html

**Comment by royalkaroma** [comment]
SALUT VOILA CE QUE J AI
![Capture](https://user-images.githubusercontent.com/36032214/191998224-7ac87410-d23e-4735-9d32-249db17bd3c6.PNG)

**Comment by royalkaroma** [comment]
LA VALIDATION C EST OK MAIS AUCUN MODE DE PAYMENT

**Comment by theodorspringwallee** [comment]
Dear [royalkaroma](https://github.com/royalkaroma)

As I mentioned before please contact PostFinance directly for further support: https://www.postfinance.ch/en/support/hotline.html 

Best regards

**Comment by royalkaroma** [comment]
merci infiniment je vais les contacter
